# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20161230_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
